// Generated by CoffeeScript 1.7.1
(function() {
  var init;

  init = function() {
    console.log('deploy!');
    return $('.js-btn').click(function() {
      return $('.js-main-wrapper').toggleClass('menu-activated');
    });
  };

  $(document).on('ready', init);

}).call(this);
