// Generated by CoffeeScript 1.7.1
(function() {
  var init;

  init = function() {
    console.log('start!');
    $('.js-open-filters, .js-close-filters').click(function() {
      $('.js-filters-listing').toggle();
      return false;
    });
    $('.js-main-container-overlay').click(function() {
      return $('.activate-menu').attr('checked', false);
    });
  };
  
  $(document).on('ready', init);

}).call(this);
